---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        service-node-port-range: 0-65535
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 42113
        hostPort: 42113
        listenAddress: 127.0.0.1
      - containerPort: 42114
        hostPort: 42114
        listenAddress: 127.0.0.1
